version: 2
jobs:
  build:
    machine: true
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Build application
          command:  ./gradlew --no-daemon clean nativeImage
          no_output_timeout: 45m
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}
